log:
  # Log verbosity. Possible values:
  # trace, debug, info, warning, error, fatal
  level: "debug"

# This cron expression controls how often DynGO checks
# if your public ip address has changed
cron: "0 */5 * * * *"

# Available service providers. You only need to specify those that
# you actually use.
services:
  desec:
    username: "me.dedyn.io"
    password: "SECRET_TOKEN"
    domains:
      - domain: "test.me.dedyn.io"
        v4: true  # Controls whether an A record should be created or updated
        v6: false # Controls whether an AAAA record should be created or updated
  porkbun:
    username: "API_KEY"
    password: "SECRET_KEY"
    domains:
      - domain: "test.my.domain"
        v4: true
        v6: true

# Detection mechanisms to determine your public ip address.
detection:
  v4:
    web: "https://checkipv4.dedyn.io" # Specify a url that returns your ip as a string.
    cmd: null
  v6:
    web: null
    cmd: "echo '2a00:1450:4001:831::2003'" # Use a script that returns your ip as a string.
