log:
  level: "debug"
cron: "0 */5 * * * *"
services:
  desec:
    username: "me.dedyn.io"
    password: "SECRET_TOKEN"
    domains:
      - domain: "test.me.dedyn.io"
        v4: true
        v6: false
  porkbun:
    username: "API_KEY"
    password: "SECRET_KEY"
    domains:
      - domain: "test.my.domain"
        v4: true
        v6: true
detection:
  v4:
    web: "https://checkipv4.dedyn.io"
    cmd: null
  v6:
    web: null
    cmd: "echo '2a00:1450:4001:831::2003'"
