log:
  # Log verbosity. Possible values:
  # trace, debug, info, warning, error, fatal
  level: "debug"

# Available service providers. You only need to specify those that
# you actually use.
services:
  desec:
    username: "me.dedyn.io"
    password: "SECRET_TOKEN"
    domains:
      - name: "test.me.dedyn.io"
        v4: true  # Controls whether an A record should be created or updated
        v6: false # Controls whether an AAAA record should be created or updated
      - name: "test2.me.dedyn.io"
        v4: false
        v6: false
  porkbun:
    username: "API_KEY"
    password: "SECRET_KEY"
    domains:
      - name: "test.my.domain"
        v4: true
        v6: true

detection:
  # When should DynGO check if your wan ip address has changed?
  triggers:
    # check periodically
    cron: "0 */5 * * * *"

  # How should DynGO check if your wan ip address has changed?
  strategies:
    v4:
      web: "https://checkipv4.dedyn.io" # Specify a url that returns your ip as a string.
      cmd: null
    v6:
      web: null
      cmd: "echo '2a00:1450:4001:831::2003'" # Use a script that returns your ip as a string.
